<?php

namespace App\Tests\Controller;

use PHPUnit\Framework\TestCase;
use App\Controller\إدارة التخزينController;
use App\Repository\إدارة التخزينRepository;
use App\Entity\إدارة التخزين;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\QueryException;
use Doctrine\ORM\NonUniqueResultException;
use PHPUnit\Framework\MockObject\MockObject;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;

class Testإدارة التخزين extends TestCase
{
    private $controller;
    private $repository;
    private $entityManager;
    private $request;

    protected function setUp(): void
    {
        $this->repository = $this->createMock(EntityRepository::class);
        $this->entityManager = $this->createMock(EntityManagerInterface::class);
        $this->entityManager->method('getRepository')->willReturn($this->repository);
        $this->repository->method('find')->willReturn(null);
        $this->repository->method('findAll')->willReturn([]);
        $this->repository->method('findOneBy')->willReturn(null);
        $this->repository->method('findBy')->willReturn([]);
        $this->repository->method('getOneOrNullResult')->willReturn(null);
        $this->repository->method('getManyToManyResult')->willReturn([]);
        $this->repository->method('getSingleResult')->willReturn(null);
        $this->repository->method('count')->willReturn(0);
        $this->repository->method('createQueryBuilder')->willReturn($this->createMock(\Doctrine\ORM\Query\QueryBuilder::class));
        $this->repository->method('getOneOrNullResult')->willReturn(null);
        $this->repository->method('getManyToManyResult')->willReturn([]);
        $this->repository->method('getSingleResult')->willReturn(null);
        $this->repository->method('count')->willReturn(0);
        $this->entityManager->method('persist')->willReturn(null);
        $this->entityManager->method('flush')->willReturn(null);
        $this->entityManager->method('remove')->willReturn(null);
        $this->entityManager->method('merge')->willReturn(null);
        $this->entityManager->method('clear')->willReturn(null);
        $this->entityManager->method('detach')->willReturn(null);
        $this->entityManager->method('contains')->willReturn(false);
        $this->entityManager->method('getUnitOfWork')->willReturn(null);
        $this->entityManager->method('getMetadataFactory')->willReturn(null);
        $this->entityManager->method('getFilters')->willReturn(null);
        $this->entityManager->method('getFilters()->getFilterNames')->willReturn([]);
        $this->entityManager->method('getFilters()->getFilters')->willReturn([]);
        $this->entityManager->method('getFilters()->hasFilter')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilter')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameter')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameter')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameterName')->willReturn(false);
        $this->entityManager->method('getFilters()->getFilterParameterName')->willReturn(null);
        $this->entityManager->method('getFilters()->hasFilterParameter